###################################### Глобальные переменные на весь pipeline
variables:
  STREAM_COUNT:
    value: "5"
    description: "Укажите количество потоков для запуска автотестов"
  STAGE:
    value: "1"
    description: "Укажите номер стенда"
  MESSENGER_ENDPOINT: 'https://msg.vseinstrumenti.ru/api/v4/'
  CHANNEL_ID: '5ygdz4813jgp3b9x8j3yzzw6be'
  ALLURE_LAUNCH_NAME: 'Запуск автотестов на ${STAGE} стенде - ${CI_COMMIT_REF_NAME} - ${GITLAB_USER_LOGIN}'
  DB_HOST: 'intgr-test-db-tms-api.ox1.dev'
  DB_NAME: 'tms-api'


###################################### Докер образ
image: harbor.vseinstrumenti.ru/dockerhub/library/python:3.12-bullseye

###################################### Стадии pipeline
stages:
  - install
  - linters
  - tests
  - report

###################################### Подключаемые конфиги
include:
  - local: .gitlab/install.yaml
  - local: .gitlab/linter.yaml
  - local: .gitlab/manualRunTests.yaml
  - local: .gitlab/stageConfig.yaml

