###################################### Шаблон с параметрами тестовых стендов
.var-test-1:
  variables:
    STAGE: 1

.var-test-2:
  variables:
    STAGE: 2

.var-test-3:
  variables:
    STAGE: 3

.var-test-4:
  variables:
    STAGE: 4